sudo: false

deploy:
  provider: gae
  keyfile: gae-client-secret.json
  project: hollowverse-c9cad
  version: $TRAVIS_BRANCH
  no_promote: true # Do not route all traffic to this version
  on:
    all_branches: true

script:
  - echo "No script to run"

before_install:
  # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then 
      openssl aes-256-cbc -K $encrypted_744738cd0ff8_key -iv $encrypted_744738cd0ff8_iv
        -in gae-client-secret.json.enc -out gae-client-secret.json -d
      ;
    fi

notifications:
  email: false

