services:
  - docker

script:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then 
      docker run
          # Mount the project source inside the container at /hollowverse
          -v $(pwd):/hollowverse

          # Pass the following environment variables to the container
          -e BRANCH=$TRAVIS_BRANCH 
          -e PROJECT=hollowverse-c9cad
          -e IV=$encrypted_744738cd0ff8_iv
          -e KEY=$encrypted_744738cd0ff8_key

        # Use this image for the container
        hollowverse/hollowverse-gae
      ;
    fi

notifications:
  email: false

