runtime: custom
env: flex

skip_files:
  - node_modules
  - client/src
  - server/src
  - client/.babelrc
  - stats.json
  - .log
  - .vscode
  - .git
  - deploy.js

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 6

resources:
  cpu: 1
  memory_gb: 0.9
