version: 0.2

env:
  variables:
    BRANCH: "master"
  parameter-store:
    ENC_PASS_SUMO: "ENC_PASS_SUMO"

phases:
  build:
    commands:
      - docker run
        -v $(pwd):/repo
        -e BRANCH
        -e ENC_PASS_SUMO
        hollowverse/hollowverse-gae

artifacts:
  files:
    - client/dist/**/*
    - server/dist/**/*
    - secrets/**/*
    - common/**/*
    - yarn.lock
    - package.lock
    - Dockerfile
