version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::901881000271:role/service-role/HollowverseCodeBuildRole
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/docker:1.12.1
  Timeout: 10

env:
  parameter-store:
    ENC_PASS_SUMO: "ENC_PASS_SUMO"

phases:
  build:
    commands:
      - docker run
        -v $(pwd):/repo
        -e ENC_PASS_SUMO
        -e IS_PULL_REQUEST=false
        -e CODEBUILD_SOURCE_VERSION
        -e CODEBUILD_RESOLVED_SOURCE_VERSION
        hollowverse/build-env

artifacts:
  files:
    - client/dist/**/*
    - server/dist/**/*
    - secrets/**/*
    - common/**/*
    - yarn.lock
    - package.json
    - env.json
    - Dockerfile
    - .dockerignore
