version: 0.2

phases:
  build:
    commands:
      - node deploy.js

artifacts:
  files:
    - client/dist/**/*
    - server/dist/**/*
    - secrets/**/*
    - common/**/*
    - yarn.lock
    - package.lock
    - Dockerfile
