version: "3.3"

services:
  web_app:
    network_mode: "host"
    restart: always
    build:
      dockerfile: Dockerfile-dev
      context: .
    ports:
      - "${PORT:-8081}" # Main Server
      - "${APP_SERVER_PORT:-3001}"
      - "${SERVER_DEBUG_PORT:-9231}" # Proxy Server Debugger
    volumes:
      - type: bind
        source: .
        target: /code
      
      - type: volume
        source: nm
        target: /code/node_modules
    environment:
      - API_ENDPOINT=${API_ENDPOINT:-https://api.hollowverse.com/graphql}
      - SERVER_DEBUG_PORT=${SERVER_DEBUG_PORT:-9231}
      - APP_SERVER_PORT=${APP_SERVER_PORT:-3001}

volumes:
  nm:

