service: website

plugins:
  - serverless-apigw-binary
  - serverless-content-encoding

custom:
  apigwBinary:
    types:
      - '*/*'
  contentEncoding:
    minimumCompressionSize: 0

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  timeout: 10
  stage: ${opt:stage, 'development'}
  region: us-east-1
  environment:
    NODE_ENV: ${self:provider.stage}
    BRANCH: ${env:BRANCH}
    COMMIT_ID: ${env:COMMIT_ID}
    SUMO_COLLECTOR_ID: ${file(./secrets/sumo.json):collectorId}
    SPLUNK_COLLECTOR_TOKEN: ${file(./secrets/splunk.json):token}

functions:
  servePages:
    handler: dist/servePages.servePages
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}
  serveLogEndpoint:
    handler: dist/serveLogEndpoint.serveLogEndpoint
    events:
      - http:
          method: POST
          path: /log

package:
  excludeDevDependencies: false
  include:
    - 'dist/**'
  exclude:
    - '**/*'


