service: website

plugins:
  - serverless-plugin-scripts
  - serverless-webpack
  - serverless-apigw-binary
  - serverless-content-encoding
  - serverless-cloudfront-invalidate

custom:
  scripts:
    hooks:
      'before:package:createDeploymentArtifacts': yarn run-s copy-defs app/build

  webpack:
    packager: 'yarn'
    webpackConfig: ./src/webpack/webpack.config.server.js
    includeModules: true

  cloudfrontInvalidate:
    distributionId: 'E3U55U3N2RXSA3'
    items:
      - '/*'
  regionAndAccount: us-east-1:251013100663
  secretsArnPrefix: arn:aws:secretsmanager:${self:custom.regionAndAccount}:secret:${self:provider.stage}
  apigwBinary:
    types:
      - '*/*'
  contentEncoding:
    minimumCompressionSize: 0

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  timeout: 10
  stage: ${opt:stage, 'development'}
  region: us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}
    STAGE: ${self:provider.stage}
    BRANCH: ${env:BRANCH}
    COMMIT_ID: ${env:COMMIT_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - '${self:custom.secretsArnPrefix}/splunk/httpCollector/website/token-*'
functions:
  servePages:
    handler: src/servePages.servePages
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}
  serveLogEndpoint:
    handler: src/serveLogEndpoint.serveLogEndpoint
    events:
      - http:
          method: POST
          path: /log

package:
  individually: true
