service: lets-encrypt

runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

env_variables:
  SERVICE_ACCOUNT: 'travis@hollowverse-c9cad.iam.gserviceaccount.com'
  DOMAIN: 'hollowverse.com'
  EMAIL: 'msafi@msafi.com'
